const root=document.getElementById('app');
let currentData=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const locale=()=>String(window.openai?.locale||document.documentElement.lang||'en').toLowerCase().startsWith('es')?'es':'en';
const tr=(en,es)=>locale()==='es'?es:en;
const head=()=>`<header class="head"><div class="brand"><span class="mark">◇</span><div><small>EXOVIA PROOFLAYER</small><strong>${tr('AI Reliability','Confiabilidad de IA')}</strong></div></div><div class="actions"><button id="fullscreen">${tr('Expand','Ampliar')}</button></div></header>`;
const foot=()=>`<footer class="foot"><span>${tr('Heuristic analysis · human review remains required','Análisis heurístico · sigue siendo necesaria la revisión humana')}</span><span>v0.3</span></footer>`;
const metric=(label,value,warn=false)=>`<span class="metric${warn?' metricWarn':''}"><small>${esc(label)}</small><strong>${esc(value)}</strong></span>`;
function issueCards(items=[]){return items.length?`<div class="issues">${items.map(i=>`<article class="issue" data-severity="${esc(i.severity)}"><i class="dot"></i><div><strong>${esc(i.title)}</strong><p>${esc(i.detail)}</p></div></article>`).join('')}</div>`:`<div class="section"><h3>${tr('No material findings','Sin hallazgos importantes')}</h3></div>`}
function renderTrust(d){const dims=d.dimensions||{};root.innerHTML=head()+`<section class="hero"><div class="score" style="--score:${Number(d.score||0)}"><strong>${esc(d.score)}</strong><span>${tr('trust','confianza')}</span></div><div><h2>${esc(d.title||tr('AI output','Resultado de IA'))}</h2><p>${esc(d.summary)}</p></div></section><div class="dimensions">${Object.entries(dims).map(([k,v])=>`<div class="dimension"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}</div>${issueCards(d.issues)}${d.unsupportedClaims?.length?`<section class="section"><h3>${tr('Claims needing stronger evidence','Afirmaciones que necesitan más evidencia')}</h3>${d.unsupportedClaims.map(x=>`<p>• ${esc(x.claim)}</p>`).join('')}</section>`:''}${d.unsupportedNumbers?.length?`<section class="section"><h3>${tr('Numbers not found in evidence','Números ausentes en la evidencia')}</h3><p>${d.unsupportedNumbers.map(esc).join(' · ')}</p></section>`:''}`+foot();bind()}
function renderCapsule(d){const redactions=Number(d.redactionCount||0);root.innerHTML=head()+`<section class="hero"><div class="mark">▣</div><div><h2>${tr('Portable context capsule','Cápsula de contexto portátil')}</h2><p>${esc(d.estimatedTokens)} ${tr('estimated tokens','tokens estimados')} · ${esc(d.evidenceSourceCount)} ${tr('sources','fuentes')} · ${esc(d.riskCount)} ${tr('risks','riesgos')}</p></div></section><div class="metricRow">${metric(tr('Privacy mode','Modo de privacidad'),tr('Redacted','Redactado'))}${metric(tr('Sensitive values replaced','Valores sensibles reemplazados'),redactions,redactions>0)}</div><section class="section"><pre>${esc(d.markdown)}</pre></section>`+foot();bind()}
function renderMap(d){root.innerHTML=head()+`<section class="hero"><div class="mark">◎</div><div><h2>${tr('NeuroCanvas map ready','Mapa NeuroCanvas listo')}</h2><p>${esc(d.nodeCount)} ${tr('nodes','nodos')} · ${esc(d.edgeCount)} ${tr('relationships','relaciones')} · ${esc(d.evidenceSourceCount)} ${tr('sources','fuentes')}</p></div></section><section class="section"><h3>${esc(d.fileName)}</h3><p>${esc(d.instructions)}</p><div class="actions"><button id="copyMap">${tr('Copy JSON','Copiar JSON')}</button><button id="downloadMap">${tr('Download for NeuroCanvas','Descargar para NeuroCanvas')}</button></div></section><section class="section"><pre>${esc(JSON.stringify(d.map,null,2))}</pre></section>`+foot();bind()}
function renderComparison(d){root.innerHTML=head()+`<section class="hero"><div class="mark">↔</div><div><h2>${tr('AI output comparison','Comparación de respuestas de IA')}</h2><p>${esc(d.recommendation)}</p></div></section><section class="ranking">${(d.ranking||[]).map((r,i)=>`<article class="rank"><span class="pos">${i+1}</span><div><strong>${esc(r.label)}</strong><div class="rankMetrics">${tr('Evidence','Evidencia')} ${esc(r.evidenceAlignment)} · ${tr('Support','Respaldo')} ${esc(r.supportCoverage)} · ${tr('Unverified numbers','Números sin verificar')} ${esc(r.unsupportedNumberCount)}</div></div><strong>${esc(r.score)}</strong></article>`).join('')}</section><section class="section"><h3>${tr('Transparent method','Método transparente')}</h3><p>${esc(d.methodology||d.limitations)}</p></section>`+foot();bind()}
function renderRoute(d){root.innerHTML=head()+`<section class="hero"><div class="mark">◎</div><div><small>${tr('RECOMMENDED ROUTE','RUTA RECOMENDADA')}</small><div class="route">${esc(String(d.mode||'').replaceAll('_',' ').toUpperCase())}</div><p>${esc(d.reason)}</p></div></section><section class="section"><h3>${tr('Controls','Controles')}</h3>${(d.controls||[]).map(x=>`<p>✓ ${esc(x)}</p>`).join('')}<p>${tr('Context budget','Presupuesto de contexto')}: ${esc(d.contextBudget)} tokens</p></section>`+foot();bind()}
function renderProof(d){const redactions=Number(d.redactionCount||0);root.innerHTML=head()+`<section class="hero"><div class="mark">#</div><div><h2>${tr('Verified Proof Pack','Paquete de prueba verificable')}</h2><p>${esc(d.evidenceSourceCount)} ${tr('sources','fuentes')} · ${tr('trust','confianza')} ${esc(d.trustScore)}</p></div></section><div class="metricRow">${metric(tr('Sensitive values replaced','Valores sensibles reemplazados'),redactions,redactions>0)}${metric(tr('Human approval','Aprobación humana'),tr('Required','Obligatoria'))}</div><section class="section"><h3>SHA-256</h3><div class="hash">${esc(d.hash)}</div></section><section class="section"><h3>${tr('Governance','Gobernanza')}</h3><p>✓ ${tr('Sensitive values redacted before export','Valores sensibles redactados antes de exportar')}</p><p>✓ ${tr('Human approval required','Aprobación humana obligatoria')}</p><p>✓ ${tr('No external actions executed','No se ejecutaron acciones externas')}</p></section>`+foot();bind()}
function render(data){if(!data)return;currentData=data;({trust_scan:renderTrust,context_capsule:renderCapsule,neurocanvas_map:renderMap,comparison:renderComparison,safe_route:renderRoute,proof_pack:renderProof}[data.kind]||renderTrust)(data)}
function bind(){document.getElementById('fullscreen')?.addEventListener('click',()=>window.openai?.requestDisplayMode?.({mode:'fullscreen'}));document.getElementById('copyMap')?.addEventListener('click',async()=>navigator.clipboard?.writeText(JSON.stringify(currentData?.map,null,2)));document.getElementById('downloadMap')?.addEventListener('click',()=>{if(!currentData?.map)return;const blob=new Blob([`${JSON.stringify(currentData.map,null,2)}\n`],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=currentData.fileName||'exovia-neurocanvas-map.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)})}
render(window.openai?.toolOutput);
window.addEventListener('openai:set_globals',e=>render(e.detail?.globals?.toolOutput??window.openai?.toolOutput),{passive:true});
window.addEventListener('message',e=>{if(e.source!==window.parent)return;const m=e.data;if(m?.jsonrpc==='2.0'&&m.method==='ui/notifications/tool-result')render(m.params?.structuredContent)},{passive:true});
