const root=document.getElementById('app');
let currentData=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const locale=()=>String(window.openai?.locale||document.documentElement.lang||'en').toLowerCase().startsWith('es')?'es':'en';
const tr=(en,es)=>locale()==='es'?es:en;
const head=()=>`<header class="head"><div class="brand"><span class="mark">◇</span><div><small>EXOVIA PROOFLAYER</small><strong>${tr('AI Reliability','Confiabilidad de IA')}</strong></div></div><div class="actions"><button id="fullscreen">${tr('Expand','Ampliar')}</button></div></header>`;
const foot=()=>`<footer class="foot"><span>${tr('Heuristic analysis · human review remains required','Análisis heurístico · sigue siendo necesaria la revisión humana')}</span><span>v0.5</span></footer>`;
const metric=(label,value,warn=false)=>`<span class="metric${warn?' metricWarn':''}"><small>${esc(label)}</small><strong>${esc(value)}</strong></span>`;
function issueCards(items=[]){return items.length?`<div class="issues">${items.map(i=>`<article class="issue" data-severity="${esc(i.severity)}"><i class="dot"></i><div><strong>${esc(i.title)}</strong><p>${esc(i.detail)}</p></div></article>`).join('')}</div>`:`<div class="section"><h3>${tr('No material findings','Sin hallazgos importantes')}</h3></div>`}
function renderTrust(d){const dims=d.dimensions||{};root.innerHTML=head()+`<section class="hero"><div class="score" style="--score:${Number(d.score||0)}"><strong>${esc(d.score)}</strong><span>${tr('trust','confianza')}</span></div><div><h2>${esc(d.title||tr('AI output','Resultado de IA'))}</h2><p>${esc(d.summary)}</p></div></section><div class="dimensions">${Object.entries(dims).map(([k,v])=>`<div class="dimension"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}</div>${issueCards(d.issues)}${d.unsupportedClaims?.length?`<section class="section"><h3>${tr('Claims needing stronger evidence','Afirmaciones que necesitan más evidencia')}</h3>${d.unsupportedClaims.map(x=>`<p>• ${esc(x.claim)}</p>`).join('')}</section>`:''}${d.unsupportedNumbers?.length?`<section class="section"><h3>${tr('Numbers not found in evidence','Números ausentes en la evidencia')}</h3><p>${d.unsupportedNumbers.map(esc).join(' · ')}</p></section>`:''}`+foot();bind()}
function renderCapsule(d){const redactions=Number(d.redactionCount||0);root.innerHTML=head()+`<section class="hero"><div class="mark">▣</div><div><h2>${tr('Portable context capsule','Cápsula de contexto portátil')}</h2><p>${esc(d.estimatedTokens)} ${tr('estimated tokens','tokens estimados')} · ${esc(d.evidenceSourceCount)} ${tr('sources','fuentes')} · ${esc(d.riskCount)} ${tr('risks','riesgos')}</p></div></section><div class="metricRow">${metric(tr('Privacy mode','Modo de privacidad'),tr('Redacted','Redactado'))}${metric(tr('Sensitive values replaced','Valores sensibles reemplazados'),redactions,redactions>0)}</div><section class="section"><pre>${esc(d.markdown)}</pre></section>`+foot();bind()}
function renderExo(d){const redactions=Number(d.redactionCount||0);root.innerHTML=head()+`<section class="hero"><div class="mark">EXO</div><div><h2>${tr('Inspectable capability pack','Paquete de capacidad inspeccionable')}</h2><p>${esc(d.sourceCount)} ${tr('sources','fuentes')} · ${esc(d.chunkCount)} ${tr('on-demand chunks','fragmentos bajo demanda')} · ${esc(d.estimatedInitialReductionPercent)}% ${tr('estimated initial context reduction','reducción inicial estimada de contexto')}</p></div></section><div class="metricRow">${metric(tr('Procedures','Procedimientos'),d.procedureCount)}${metric(tr('Constraints','Restricciones'),d.constraintCount)}${metric(tr('Redactions','Redacciones'),redactions,redactions>0)}</div><section class="section"><h3>${esc(d.fileName)}</h3><p>${esc(d.instructions)}</p><div class="actions"><button id="copyExo">${tr('Copy package','Copiar paquete')}</button><button id="downloadExo">${tr('Download .exo','Descargar .exo')}</button></div></section><section class="section"><h3>SHA-256</h3><div class="hash">${esc(d.hash)}</div></section><section class="section"><h3>${tr('Safety contract','Contrato de seguridad')}</h3><p>✓ ${tr('Source and chunk IDs retained','IDs de fuente y fragmento preservados')}</p><p>✓ ${tr('Human approval required','Aprobación humana obligatoria')}</p><p>✓ ${tr('No external actions executed','No se ejecutaron acciones externas')}</p><p>✓ ${tr('No third-party runtime code bundled','No incorpora runtime de terceros')}</p><p>ⓘ ${tr('Source rights must be reviewed by the user','El usuario debe revisar los derechos sobre las fuentes')}</p></section>`+foot();bind()}
function renderMap(d){root.innerHTML=head()+`<section class="hero"><div class="mark">◎</div><div><h2>${tr('NeuroCanvas map ready','Mapa NeuroCanvas listo')}</h2><p>${esc(d.nodeCount)} ${tr('nodes','nodos')} · ${esc(d.edgeCount)} ${tr('relationships','relaciones')} · ${esc(d.evidenceSourceCount)} ${tr('sources','fuentes')}</p></div></section><section class="section"><h3>${esc(d.fileName)}</h3><p>${esc(d.instructions)}</p><div class="actions"><button id="copyMap">${tr('Copy JSON','Copiar JSON')}</button><button id="downloadMap">${tr('Download for NeuroCanvas','Descargar para NeuroCanvas')}</button></div></section><section class="section"><pre>${esc(JSON.stringify(d.map,null,2))}</pre></section>`+foot();bind()}
function renderComparison(d){root.innerHTML=head()+`<section class="hero"><div class="mark">↔</div><div><h2>${tr('AI output comparison','Comparación de respuestas de IA')}</h2><p>${esc(d.recommendation)}</p></div></section><section class="ranking">${(d.ranking||[]).map((r,i)=>`<article class="rank"><span class="pos">${i+1}</span><div><strong>${esc(r.label)}</strong><div class="rankMetrics">${tr('Evidence','Evidencia')} ${esc(r.evidenceAlignment)} · ${tr('Support','Respaldo')} ${esc(r.supportCoverage)} · ${tr('Unverified numbers','Números sin verificar')} ${esc(r.unsupportedNumberCount)}</div></div><strong>${esc(r.score)}</strong></article>`).join('')}</section><section class="section"><h3>${tr('Transparent method','Método transparente')}</h3><p>${esc(d.methodology||d.limitations)}</p></section>`+foot();bind()}
function renderRoute(d){root.innerHTML=head()+`<section class="hero"><div class="mark">◎</div><div><small>${tr('RECOMMENDED ROUTE','RUTA RECOMENDADA')}</small><div class="route">${esc(String(d.mode||'').replaceAll('_',' ').toUpperCase())}</div><p>${esc(d.reason)}</p></div></section><section class="section"><h3>${tr('Controls','Controles')}</h3>${(d.controls||[]).map(x=>`<p>✓ ${esc(x)}</p>`).join('')}<p>${tr('Context budget','Presupuesto de contexto')}: ${esc(d.contextBudget)} tokens</p></section>`+foot();bind()}
function renderCouncil(d){const blockers=Number(d.blockingRoles?.length||0);const dissent=Number(d.dissent?.length||0);root.innerHTML=head()+`<section class="hero"><div class="score" style="--score:${Number(d.consensusScore||0)}"><strong>${esc(d.consensusScore)}</strong><span>${tr('consensus','consenso')}</span></div><div><small>EXOVIA ASSURANCE COUNCIL</small><h2>${esc(d.title)}</h2><div class="route">${esc(String(d.verdict||'').toUpperCase())}</div><p>${esc(d.summary)}</p></div></section><div class="metricRow">${metric(tr('Review lenses','Perspectivas'),d.roles?.length||0)}${metric(tr('Blocking roles','Roles bloqueantes'),blockers,blockers>0)}${metric(tr('Visible dissent','Disenso visible'),dissent,dissent>0)}</div><section class="ranking">${(d.roles||[]).map((r,i)=>`<article class="rank"><span class="pos">${i+1}</span><div><strong>${esc(r.label)}</strong><div class="rankMetrics">${esc(String(r.status).toUpperCase())} · ${esc(r.purpose)}</div></div><strong>${esc(r.score)}</strong></article>`).join('')}</section>${d.nextBestActions?.length?`<section class="section"><h3>${tr('Prioritized human actions','Acciones humanas priorizadas')}</h3>${d.nextBestActions.map(x=>`<p>• ${esc(x)}</p>`).join('')}</section>`:''}<section class="section"><h3>${tr('Inspectable handoff','Transferencia inspeccionable')}</h3><p>${esc(d.exialPulses?.length||0)} ExiaL pulses · ${esc(d.exirEvents?.length||0)} EXIR events · ${tr('no external actions executed','no se ejecutaron acciones externas')}</p><div class="actions"><button id="downloadCouncil">${tr('Download council report','Descargar informe')}</button><button id="downloadCouncilMap">${tr('Open in NeuroCanvas','Abrir en NeuroCanvas')}</button></div></section><section class="section"><h3>SHA-256</h3><div class="hash">${esc(d.integrity?.hash)}</div><p>${esc(d.limitations)}</p></section>`+foot();bind()}
function renderProof(d){const redactions=Number(d.redactionCount||0);root.innerHTML=head()+`<section class="hero"><div class="mark">#</div><div><h2>${tr('Verified Proof Pack','Paquete de prueba verificable')}</h2><p>${esc(d.evidenceSourceCount)} ${tr('sources','fuentes')} · ${tr('trust','confianza')} ${esc(d.trustScore)}</p></div></section><div class="metricRow">${metric(tr('Sensitive values replaced','Valores sensibles reemplazados'),redactions,redactions>0)}${metric(tr('Human approval','Aprobación humana'),tr('Required','Obligatoria'))}</div><section class="section"><h3>SHA-256</h3><div class="hash">${esc(d.hash)}</div></section><section class="section"><h3>${tr('Governance','Gobernanza')}</h3><p>✓ ${tr('Sensitive values redacted before export','Valores sensibles redactados antes de exportar')}</p><p>✓ ${tr('Human approval required','Aprobación humana obligatoria')}</p><p>✓ ${tr('No external actions executed','No se ejecutaron acciones externas')}</p></section>`+foot();bind()}
function render(data){if(!data)return;currentData=data;({trust_scan:renderTrust,context_capsule:renderCapsule,exo_capability_pack:renderExo,neurocanvas_map:renderMap,comparison:renderComparison,safe_route:renderRoute,assurance_council:renderCouncil,proof_pack:renderProof}[data.kind]||renderTrust)(data)}
function downloadJson(value,fileName){const blob=new Blob([`${JSON.stringify(value,null,2)}\n`],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=fileName;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
function bind(){document.getElementById('fullscreen')?.addEventListener('click',()=>window.openai?.requestDisplayMode?.({mode:'fullscreen'}));document.getElementById('copyMap')?.addEventListener('click',async()=>navigator.clipboard?.writeText(JSON.stringify(currentData?.map,null,2)));document.getElementById('downloadMap')?.addEventListener('click',()=>currentData?.map&&downloadJson(currentData.map,currentData.fileName||'exovia-neurocanvas-map.json'));document.getElementById('copyExo')?.addEventListener('click',async()=>navigator.clipboard?.writeText(JSON.stringify(currentData?.package,null,2)));document.getElementById('downloadExo')?.addEventListener('click',()=>currentData?.package&&downloadJson(currentData.package,currentData.fileName||'exovia-capability-pack.exo'));document.getElementById('downloadCouncil')?.addEventListener('click',()=>currentData&&downloadJson(currentData,'exovia-assurance-council.json'));document.getElementById('downloadCouncilMap')?.addEventListener('click',()=>currentData?.neurocanvasHandoff?.map&&downloadJson(currentData.neurocanvasHandoff.map,currentData.neurocanvasHandoff.fileName||'exovia-assurance-council-map.json'))}
render(window.openai?.toolOutput);
window.addEventListener('openai:set_globals',e=>render(e.detail?.globals?.toolOutput??window.openai?.toolOutput),{passive:true});
window.addEventListener('message',e=>{if(e.source!==window.parent)return;const m=e.data;if(m?.jsonrpc==='2.0'&&m.method==='ui/notifications/tool-result')render(m.params?.structuredContent)},{passive:true});
